Improved script.

diff --git a/freebsd/hipercontracer/test-packaging b/freebsd/hipercontracer/test-packaging
--- a/freebsd/hipercontracer/test-packaging
+++ b/freebsd/hipercontracer/test-packaging
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # Free Packaging Test Script
-# Copyright (C) 2010-2020 by Thomas Dreibholz
+# Copyright (C) 2010-2021 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,22 +18,22 @@
 #
 # Contact: dreibh@iem.uni-due.de
 
-PACKAGE=`cat Makefile | grep PORTNAME= | sed -e "s/^PORTNAME=//g" | tr -d " \t"`
-UPSTREAM_VERSION=`cat Makefile | grep PORTVERSION= | sed -e "s/^PORTVERSION=//g" | tr -d " \t"`
-PORTREVISION=`cat Makefile | grep PORTREVISION= | sed -e "s/^PORTREVISION=//g" | tr -d " \t"`
-CATEGORY=`cat Makefile | grep CATEGORIES= | sed -e "s/^CATEGORIES=//g" | tr -d " \t"`
+PACKAGE=`cat Makefile | grep "^PORTNAME=" | sed -e "s/^PORTNAME=//g" | tr -d " \t"`
+UPSTREAM_VERSION=`cat Makefile | grep "^PORTVERSION=" | sed -e "s/^PORTVERSION=//g" | tr -d " \t"`
+PORTREVISION=`cat Makefile | grep "^PORTREVISION=" | sed -e "s/^PORTREVISION=//g" | tr -d " \t"`
+CATEGORY=`cat Makefile | grep "^CATEGORIES=" | sed -e "s/^CATEGORIES=//g" | tr -d " \t"`
 
 PACKAGE_VERSION="${UPSTREAM_VERSION}"
-if [ "$PORTREVISION" != "" ] ; then
+if [ "${PORTREVISION}" != "" ] ; then
    PACKAGE_VERSION="${UPSTREAM_VERSION}_${PORTREVISION}"
 fi
 
 
 echo "######################################################################"
-echo "PACKAGE:          $PACKAGE"
-echo "UPSTREAM_VERSION: $UPSTREAM_VERSION"
-echo "PACKAGE_VERSION:  $PACKAGE_VERSION"
-echo "CATEGORY:         $CATEGORY"
+echo "PACKAGE:          ${PACKAGE}"
+echo "UPSTREAM_VERSION: ${UPSTREAM_VERSION}"
+echo "PACKAGE_VERSION:  ${PACKAGE_VERSION}"
+echo "CATEGORY:         ${CATEGORY}"
 echo "######################################################################"
 
 
@@ -53,9 +53,12 @@ make package && \
 echo "4. ###### make deinstall ##############################################" && \
 make deinstall && \
 echo "5. ###### pkg add #####################################################" && \
-if [ -e ${PACKAGE}-${PACKAGE_VERSION}.txz ] ; then
-   mkdir /usr/ports/packages /usr/ports/packages/All
-   cp ${PACKAGE}-${PACKAGE_VERSION}.txz /usr/ports/packages/All
+if [ ! -e "work/pkg/${PACKAGE}-${PACKAGE_VERSION}.txz" ] ; then
+   echo >&2 "ERROR: Package work/pkg/${PACKAGE}-${PACKAGE_VERSION}.txz not found!"
+   exit 1
+else
+   mkdir -p /usr/ports/packages/All
+   cp work/pkg/${PACKAGE}-${PACKAGE_VERSION}.txz /usr/ports/packages/All
 fi
 pkg add /usr/ports/packages/All/${PACKAGE}-${PACKAGE_VERSION}.txz && \
 echo "6. ###### make deinstall ##############################################" && \
