Improved scripts.

diff --git a/src/TestDB/1-install-database b/src/TestDB/1-install-database
--- a/src/TestDB/1-install-database
+++ b/src/TestDB/1-install-database
@@ -127,13 +127,20 @@ elif [ "$1" == "postgresql" ] ; then
 
    sudo DEBIAN_FRONTEND=noninteractive  apt install -y postgresql-all postgresql-contrib
 
+   POSTGRESETC=`find /etc/postgresql/ -mindepth 1 -maxdepth 1 -type d | grep "[0-9]$" | sort -r | head -n1`
+   if [ "${POSTGRESETC}" == "" ] ; then
+      echo >&2 "ERROR: Cannot find the /etc/postgresql/* directory!"
+      exit 1
+   fi
+   echo "Using PostgreSQL settings in ${POSTGRESETC}!"
+
    # Enable network access:
    sudo sed \
       -e 's#^host    all             all             127.0.0.1/32            scram-sha-256#host    all             all             0.0.0.0/0               scram-sha-256#' \
       -e 's#^host    all             all             ::1/128                 scram-sha-256#host    all             all             ::/0                    scram-sha-256#' \
-      /etc/postgresql/14/main/pg_hba.conf | sudo tee /etc/postgresql/14/main/pg_hba.conf.new >/dev/null && \
-   diff --color /etc/postgresql/14/main/pg_hba.conf.new /etc/postgresql/14/main/pg_hba.conf || true && \
-   sudo mv /etc/postgresql/14/main/pg_hba.conf.new /etc/postgresql/14/main/pg_hba.conf
+      ${POSTGRESETC}/main/pg_hba.conf | sudo tee ${POSTGRESETC}/main/pg_hba.conf.new >/dev/null && \
+   diff --color ${POSTGRESETC}/main/pg_hba.conf.new ${POSTGRESETC}/main/pg_hba.conf || true && \
+   sudo mv ${POSTGRESETC}/main/pg_hba.conf.new ${POSTGRESETC}/main/pg_hba.conf
 
    sudo sed \
       -e "s%#listen_addresses = 'localhost'%listen_addresses = '*'        %" \
@@ -144,9 +151,9 @@ elif [ "$1" == "postgresql" ] ; then
       -e "s%#ssl_ciphers = '.*'%ssl_ciphers = 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256'%" \
       -e "s%#ssl_prefer_server_ciphers = on%ssl_prefer_server_ciphers = on%" \
       -e "s%#ssl_min_protocol_version = 'TLSv1.2'%ssl_min_protocol_version = 'TLSv1.3'%" \
-      /etc/postgresql/14/main/postgresql.conf | sudo tee /etc/postgresql/14/main/postgresql.conf.new >/dev/null && \
-   diff --color /etc/postgresql/14/main/postgresql.conf.new /etc/postgresql/14/main/postgresql.conf || true && \
-   sudo mv /etc/postgresql/14/main/postgresql.conf.new /etc/postgresql/14/main/postgresql.conf
+      ${POSTGRESETC}/main/postgresql.conf | sudo tee ${POSTGRESETC}/main/postgresql.conf.new >/dev/null && \
+   diff --color ${POSTGRESETC}/main/postgresql.conf.new ${POSTGRESETC}/main/postgresql.conf || true && \
+   sudo mv ${POSTGRESETC}/main/postgresql.conf.new ${POSTGRESETC}/main/postgresql.conf
 
    sudo service postgresql restart
 
