PostgreSQL configuration improvements.

diff --git a/src/TestDB/1-install-database b/src/TestDB/1-install-database
--- a/src/TestDB/1-install-database
+++ b/src/TestDB/1-install-database
@@ -68,7 +68,6 @@ fi
 
 # ###### MariaDB ############################################################
 if [ "$1" == "mariadb" ] ; then
-   # Documentation: https://www.digitalocean.com/community/tutorials/how-to-install-mariadb-on-ubuntu-22-04
    server="mariadb"
 
    # ====== Install MariaDB =================================================
@@ -95,6 +94,12 @@ if [ "$1" == "mariadb" ] ; then
       echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
       exit 1
    fi
+
+   if [ "${MARIADB_CONFIG_DIRECTORY}" == "" ] ; then
+      echo >&2 "ERROR: Cannot find the MariaDB configuration directory!"
+      exit 1
+   fi
+   echo "Using MariaDB settings in ${MARIADB_CONFIG_DIRECTORY}!"
 
    # ====== Basic configuration =============================================
    sudo ./name-in-etc-hosts "${server}.${DOMAIN}"
@@ -169,7 +174,6 @@ EOF
 
 # ###### PostgreSQL #########################################################
 elif [ "$1" == "postgresql" ] ; then
-   # Documentation: https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-22-04-quickstart
    server="postgresql"
 
    # ====== Install PostgreSQL ==============================================
@@ -192,53 +196,63 @@ elif [ "$1" == "postgresql" ] ; then
       exit 1
    fi
 
+   POSTGRES_CONFIG_DIRECTORY=""
+   if [ -d /etc/postgresql ] ; then
+      POSTGRES_CONFIG_DIRECTORY="$(find /etc/postgresql/ -mindepth 2 -maxdepth 2 -type d -name main | sort -r | head -n1)"
+   elif [ -d /var/db/postgres ] ; then
+      POSTGRES_CONFIG_DIRECTORY="$(find /var/db/postgres -mindepth 1 -maxdepth 1 -type d -name "data*" | sort -r | head -n1)"
+   elif sudo -u postgres test -d /var/lib/pgsql/data ; then
+      POSTGRES_CONFIG_DIRECTORY="/var/lib/pgsql/data"
+   fi
+   if [ "${POSTGRES_CONFIG_DIRECTORY}" == "" ] ; then
+      echo >&2 "ERROR: Cannot find the PostgreSQL configuration directory!"
+      exit 1
+   fi
+   echo "Using PostgreSQL settings in ${POSTGRES_CONFIG_DIRECTORY}!"
+
    # ====== Basic configuration =============================================
    sudo ./name-in-etc-hosts "${server}.${DOMAIN}"
    sudo ./generate-test-certificates /etc/ssl "${server}.${DOMAIN}"
 
    # PostgreSQL needs separate certificate and key files.
    # The chain is in the CA file, it must not be in the certificate file!
-   POSTGRESQL_CA_FILE="/etc/ssl/TestLevel1/certs/TestLevel1.crt"
-   POSTGRESQL_CRL_FILE="/etc/ssl/TestGlobal.crl"
-   POSTGRESQL_CRT_FILE="/etc/ssl/${server}.${DOMAIN}/${server}.${DOMAIN}.crt"
-   POSTGRESQL_KEY_FILE="/etc/ssl/${server}.${DOMAIN}/${server}.${DOMAIN}.key"
-   sudo chown postgres:postgres ${POSTGRESQL_KEY_FILE}
-
-   POSTGRESDIR=""
-   if [ -d /etc/postgresql ] ; then
-      POSTGRESDIR="$(find /etc/postgresql/ -mindepth 2 -maxdepth 2 -type d -name main | sort -r | head -n1)"
-   elif [ -d /var/db/postgres ] ; then
-      POSTGRESDIR="$(find /var/db/postgres -mindepth 1 -maxdepth 1 -type d -name "data*" | sort -r | head -n1)"
-   elif sudo -u postgres test -d /var/lib/pgsql/data ; then
-      POSTGRESDIR="/var/lib/pgsql/data"
-   fi
-   if [ "${POSTGRESDIR}" == "" ] ; then
-      echo >&2 "ERROR: Cannot find the PostgreSQL configuration directory!"
-      exit 1
-   fi
-   echo "Using PostgreSQL settings in ${POSTGRESDIR}!"
+   POSTGRES_CA_FILE="TestLevel1.crt"
+   POSTGRES_CRL_FILE="TestGlobal.crl"
+   POSTGRES_CRT_FILE="${server}.${DOMAIN}.crt"
+   POSTGRES_KEY_FILE="${server}.${DOMAIN}.key"
+   sudo cp "/etc/ssl/TestLevel1/certs/${POSTGRES_CA_FILE}" \
+      "/etc/ssl/${POSTGRES_CRL_FILE}" \
+      "/etc/ssl/${server}.${DOMAIN}/${POSTGRES_CRT_FILE}" \
+      "/etc/ssl/${server}.${DOMAIN}/${POSTGRES_KEY_FILE}" \
+      "${POSTGRES_CONFIG_DIRECTORY}"
+   sudo chown postgres:postgres \
+      "${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_CA_FILE}" \
+      "${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_CRL_FILE}" \
+      "${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_CRT_FILE}" \
+      "${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_KEY_FILE}"
+   sudo chmod 600 "${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_KEY_FILE}"
 
    # Enable network access:
    sudo -u postgres sed \
       -e 's%^\(host[ \t]*all[ \t]*all[ \t]*\)127.0.0.1/32\([ \t]*\).*$%\10.0.0.0/0   \2scram-sha-256%g' \
       -e 's%^\(host[ \t]*all[ \t]*all[ \t]*\)::1/128\([ \t]*\).*$%\1::/0   \2scram-sha-256%g' \
-      "${POSTGRESDIR}"/pg_hba.conf | sudo -u postgres tee "${POSTGRESDIR}"/pg_hba.conf.new >/dev/null && \
-   sudo -u postgres diff --color "${POSTGRESDIR}"/pg_hba.conf.new "${POSTGRESDIR}"/pg_hba.conf || true && \
-   sudo -u postgres mv -f "${POSTGRESDIR}"/pg_hba.conf.new "${POSTGRESDIR}"/pg_hba.conf
+      "${POSTGRES_CONFIG_DIRECTORY}/pg_hba.conf" | sudo -u postgres tee "${POSTGRES_CONFIG_DIRECTORY}/pg_hba.conf.new" >/dev/null && \
+   sudo -u postgres diff --color "${POSTGRES_CONFIG_DIRECTORY}/pg_hba.conf.new" "${POSTGRES_CONFIG_DIRECTORY}/pg_hba.conf" || true && \
+   sudo -u postgres mv -f "${POSTGRES_CONFIG_DIRECTORY}/pg_hba.conf.new" "${POSTGRES_CONFIG_DIRECTORY}/pg_hba.conf"
 
    sudo -u postgres sed -r \
       -e "s%#listen_addresses = 'localhost'%listen_addresses = '*'        %" \
       -e "s%^(#ssl|ssl) =.*%ssl = on%" \
-      -e "s%^(#ssl|ssl)_ca_file = '.*'%ssl_ca_file = '${POSTGRESQL_CA_FILE}'%" \
-      -e "s%^(#ssl|ssl)_crl_file = '.*'%ssl_crl_file = '${POSTGRESQL_CRL_FILE}'%" \
-      -e "s%^(#ssl|ssl)_cert_file = '.*'%ssl_cert_file = '${POSTGRESQL_CRT_FILE}'%" \
-      -e "s%^(#ssl|ssl)_key_file = '.*'%ssl_key_file = '${POSTGRESQL_KEY_FILE}'%" \
+      -e "s%^(#ssl|ssl)_ca_file = '.*'%ssl_ca_file = '${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_CA_FILE}'%" \
+      -e "s%^(#ssl|ssl)_crl_file = '.*'%ssl_crl_file = '${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_CRL_FILE}'%" \
+      -e "s%^(#ssl|ssl)_cert_file = '.*'%ssl_cert_file = '${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_CRT_FILE}'%" \
+      -e "s%^(#ssl|ssl)_key_file = '.*'%ssl_key_file = '${POSTGRES_CONFIG_DIRECTORY}/${POSTGRES_KEY_FILE}'%" \
       -e "s%#ssl_ciphers = '.*'%ssl_ciphers = 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256'%" \
       -e "s%#ssl_prefer_server_ciphers = on%ssl_prefer_server_ciphers = on%" \
       -e "s%#ssl_min_protocol_version = 'TLSv1.2'%ssl_min_protocol_version = 'TLSv1.3'%" \
-      "${POSTGRESDIR}"/postgresql.conf | sudo -u postgres tee "${POSTGRESDIR}"/postgresql.conf.new >/dev/null && \
-   sudo -u postgres diff --color "${POSTGRESDIR}"/postgresql.conf.new "${POSTGRESDIR}"/postgresql.conf || true && \
-   sudo -u postgres mv -f "${POSTGRESDIR}"/postgresql.conf.new "${POSTGRESDIR}"/postgresql.conf
+      "${POSTGRES_CONFIG_DIRECTORY}/postgresql.conf" | sudo -u postgres tee "${POSTGRES_CONFIG_DIRECTORY}/postgresql.conf.new" >/dev/null && \
+   sudo -u postgres diff --color "${POSTGRES_CONFIG_DIRECTORY}/postgresql.conf.new" "${POSTGRES_CONFIG_DIRECTORY}/postgresql.conf" || true && \
+   sudo -u postgres mv -f "${POSTGRES_CONFIG_DIRECTORY}/postgresql.conf.new" "${POSTGRES_CONFIG_DIRECTORY}/postgresql.conf"
 
    sudo service postgresql restart
    sleep 5
@@ -249,7 +263,6 @@ elif [ "$1" == "postgresql" ] ; then
 
 # ###### MongoDB ############################################################
 elif [ "$1" == "mongodb" ] ; then
-   # Documentation: https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/
    server="mongodb"
 
    # ====== Install MongoDB =================================================
