Improved script.

diff --git a/src/TestDB/1-install-database b/src/TestDB/1-install-database
--- a/src/TestDB/1-install-database
+++ b/src/TestDB/1-install-database
@@ -1,8 +1,26 @@
 #!/bin/bash -e
 
-if [ $# -ne 1 ] ; then
-   echo >&2 "Usage: $0 mariadb|postgres|mongodb"
+if [ $# -ne 2 ] ; then
+   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql users.conf"
    exit 1
+fi
+if [ ! -e $2 ] ; then
+   echo >&2 "ERROR: Use configuration $2 does not exist!"
+fi
+
+ROOT_PASSWORD="!root!"
+MAINTAINER_PASSWORD="!maintainer!"
+IMPORTER_PASSWORD="!importer!"
+RESEARCHER_PASSWORD="!researcher!"
+. ./$2
+
+if [ "${ROOT_PASSWORD}"       = "!root!"       -o \
+     "${MAINTAINER_PASSWORD}" = "!maintainer!" -o \
+     "${IMPORTER_PASSWORD}"   = "!importer!"   -o \
+     "${RESEARCHER_PASSWORD}" = "!researcher!" ] ; then
+   echo >&2 "DO NOT USE THE EXAMPLE PASSWORDS!"
+# FIXME! ????
+# exit 1
 fi
 
 
@@ -82,6 +100,19 @@ elif [ "$1" == "mongodb" ] ; then
    fi
    sudo apt-get update -qq
    sudo apt-get install -y mongodb-org
+
+   mongosh --quiet <<EOF
+use admin
+db.dropUser("root")
+db.createUser({ user: "root",
+                pwd: "${ROOT_PASSWORD}",
+                roles: [
+                   "userAdminAnyDatabase",
+                   "dbAdminAnyDatabase",
+                   "readWriteAnyDatabase",
+                   "clusterAdmin"
+                ] })
+EOF
 
    sudo sed \
       -e "s#  bindIp: 127.0.0.1#  ipv6: true\n  bindIpAll: true\n  ssl:\n    mode: requireSSL\n    PEMKeyFile: ${PEM_FILE}\n    disabledProtocols: TLS1_0,TLS1_1,TLS1_2#" \
