Improved test script.

diff --git a/src/TestDB/1-install-database b/src/TestDB/1-install-database
--- a/src/TestDB/1-install-database
+++ b/src/TestDB/1-install-database
@@ -242,7 +242,14 @@ elif [ "$1" == "postgresql" ] ; then
 
    # ====== Basic configuration =============================================
    sudo ./name-in-etc-hosts "${server}.${DOMAIN}"
-   sudo ./generate-test-certificates /etc/ssl "${server}.${DOMAIN}"
+   if [ -x /usr/share/system-tools/generate-test-certificates ] ; then
+      sudo /usr/share/system-tools/generate-test-certificates /etc/ssl "${server}.${DOMAIN}"
+   elif [ -x /usr/local/share/system-tools/generate-test-certificates ] ; then
+      sudo /usr/local/share/system-tools/generate-test-certificates /etc/ssl "${server}.${DOMAIN}"
+   else
+      echo >&2 "ERROR: generate-test-certificates (part of the System-Tools package) is not installed!"
+      exit 1
+   fi
 
    # PostgreSQL needs separate certificate and key files.
    # The chain is in the CA file, it must not be in the certificate file!
@@ -389,7 +396,14 @@ EOF
 
    # ====== Basic configuration =============================================
    sudo ./name-in-etc-hosts "${server}.${DOMAIN}"
-   sudo ./generate-test-certificates /etc/ssl "${server}.${DOMAIN}"
+   if [ -x /usr/share/system-tools/generate-test-certificates ] ; then
+      sudo /usr/share/system-tools/generate-test-certificates /etc/ssl "${server}.${DOMAIN}"
+   elif [ -x /usr/local/share/system-tools/generate-test-certificates ] ; then
+      sudo /usr/local/share/system-tools/generate-test-certificates /etc/ssl "${server}.${DOMAIN}"
+   else
+      echo >&2 "ERROR: generate-test-certificates (part of the System-Tools package) is not installed!"
+      exit 1
+   fi
 
    # MongoDB wants key + certificate + chain (in this order!) in the PEM file:
    MONGODB_CA_FILE="TestLevel1.crt"
