Improved test scripts.

diff --git a/src/TestDB/5-perform-hpct-importer-test b/src/TestDB/5-perform-hpct-importer-test
--- a/src/TestDB/5-perform-hpct-importer-test
+++ b/src/TestDB/5-perform-hpct-importer-test
@@ -35,15 +35,21 @@ set -o nounset
 set -o errexit
 
 
-if [ $# -lt 1 ] ; then
-   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql"
+if [ $# -ne 2 ] ; then
+   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql users.conf"
    exit 1
 fi
+if [ ! -e "$2" ] ; then
+   echo >&2 "ERROR: Use configuration $2 does not exist!"
+fi
 
-IMPORTER_CONFIG="${HOME}/importer-testdb.conf"
-# Access to database as "importer" user:
+DATABASE="just_a_test_database"
+# shellcheck disable=SC1090
+. "$2"
+
 DBMS="$1"
-DATABASE_CONFIG="${HOME}/testdb-importer-${DBMS}.conf"
+DATABASE_CONFIG="${HOME}/${DATABASE}-importer-${DBMS}.conf"
+IMPORTER_CONFIG="${HOME}/importer-${DATABASE}.conf"
 
 if [ ! -v VALGRIND_CMD ] ; then
    VALGRIND_CMD=""
@@ -74,7 +80,7 @@ if [ -e "${DATABASE_CONFIG}" ] ; then
       -C "${IMPORTER_CONFIG}" \
       -D "${DATABASE_CONFIG}" \
       --quit-when-idle \
-      --loglevel 0
+      --loglevel 2
 
 
 # ###### Error ##############################################################
diff --git a/src/TestDB/6-perform-hpct-query-test b/src/TestDB/6-perform-hpct-query-test
--- a/src/TestDB/6-perform-hpct-query-test
+++ b/src/TestDB/6-perform-hpct-query-test
@@ -35,14 +35,20 @@ set -o nounset
 set -o errexit
 
 
-if [ $# -lt 1 ] ; then
-   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql"
+if [ $# -ne 2 ] ; then
+   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql users.conf"
    exit 1
 fi
+if [ ! -e "$2" ] ; then
+   echo >&2 "ERROR: Use configuration $2 does not exist!"
+fi
 
-# Access to database as "researcher" user:
+DATABASE="just_a_test_database"
+# shellcheck disable=SC1090
+. "$2"
+
 DBMS="$1"
-DATABASE_CONFIG="${HOME}/testdb-researcher-${DBMS}.conf"
+DATABASE_CONFIG="${HOME}/${DATABASE}-researcher-${DBMS}.conf"
 
 if [ ! -v VALGRIND_CMD ] ; then
    VALGRIND_CMD=""
