First part of options handling improvements.

diff --git a/src/dbshell b/src/dbshell
--- a/src/dbshell
+++ b/src/dbshell
@@ -34,16 +34,32 @@ set -euo pipefail
 
 # ###### Usage ##############################################################
 usage () {
-   echo >&2 "Usage: $0 configuration_file [-h|--help] [-d|--dry-run] [-q|--quiet] [-B|--write-dbeaver-config file_prefix]"
+   echo >&2 "Usage: $0 configuration_file [-d|--dry-run] [-q|--quiet] [-w|--verbose] [-B|--write-dbeaver-config file_prefix] [-h|--help] [-v|--version]"
    exit 1
 }
+
+
+# ###### Version ############################################################
+version () {
+   echo "DBShell @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   exit 0
+}
+
 
 
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-options="$(${GETOPT} -o hdqB: --long help,dry-run,quiet,write-dbeaver-config: -a -- "$@")"
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
+options="$(${GETOPT} -o dqwB:hv --long dry-run,quiet,verbose,write-dbeaver-config:,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
    usage
@@ -57,23 +73,35 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -B | --write-dbeaver-config)
          DBEAVER_CONFIG_PREFIX="$2"
-         shift 2
+         shift
          ;;
       -d | --dry-run)
          DRY_RUN=1
-         shift
          ;;
       -q | --quiet)
          QUIET=1
-         shift
+         ;;
+      -w | --verbose)
+         QUIET=0
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      -v | --version)
+         version
          ;;
       --)
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
+         ;;
   esac
 done
-if [ $# -lt 1 ] ; then
+if [ $# -ne 1 ] ; then
    usage
 fi
 CONFIGURATION_FILE="$1"
diff --git a/src/encrypt-dbeaver-configuration b/src/encrypt-dbeaver-configuration
--- a/src/encrypt-dbeaver-configuration
+++ b/src/encrypt-dbeaver-configuration
@@ -32,27 +32,77 @@
 set -euo pipefail
 
 
+# ###### Usage ##############################################################
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 plain_dbeaver_credentials_config_json encrypted_dbeaver_credentials_config_json [-h|--help] [-v|--version]"
+   exit "${exitCode}"
+}
+
+
+# ###### Version ############################################################
+version () {
+   echo "Encrypt-DBeaver-Configuration @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   exit 0
+}
+
+
+
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-if [ $# -ne 2 ] ; then
-   echo >&2 "Usage: $0 plain_dbeaver_credentials_config_json encrypted_dbeaver_credentials_config_json"
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} installed!"
    exit 1
 fi
-
-inputFile="$1"
-if [ "${inputFile}" == "-" ] ; then
-   inputFile="/dev/stdin"
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
 fi
-outputFile="$2"
-if [ "${outputFile}" == "-" ] ; then
-   outputFile="/dev/stdout"
+options="$(${GETOPT} -o hv --long help,version -a -- "$@")"
+# shellcheck disable=SC2181
+if [[ $? -ne 0 ]]; then
+   usage 1
+fi
+
+eval set -- "${options}"
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -h | --help)
+         usage 0
+         ;;
+      -v | --version)
+         version
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
+         ;;
+  esac
+done
+if [ $# -ne 2 ] ; then
+   usage 1
+fi
+
+INPUT_FILE="$1"
+if [ "${INPUT_FILE}" == "-" ] ; then
+   INPUT_FILE="/dev/stdin"
+fi
+OUTPUT_FILE="$2"
+if [ "${OUTPUT_FILE}" == "-" ] ; then
+   OUTPUT_FILE="/dev/stdout"
 fi
 
 # ====== Process file =======================================================
 (
    dd if=/dev/urandom of="/dev/stdout" bs=16 count=1 status=none 2>/dev/null   # 16 bytes random number
-   cat "${inputFile}"
+   cat "${INPUT_FILE}"
 ) | openssl aes-128-cbc \
    -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 \
-   -in /dev/stdin >"${outputFile}"
+   -in /dev/stdin >"${OUTPUT_FILE}"
diff --git a/src/hpct-node-removal b/src/hpct-node-removal
--- a/src/hpct-node-removal
+++ b/src/hpct-node-removal
@@ -34,21 +34,66 @@ set -euo pipefail
 
 # ###### Usage ##############################################################
 usage () {
-   echo >&2 "Usage: $0 node_id [-h|--help] [-r|--remove-data]"
+   echo >&2 "Usage: $0 node_id [-r|--remove-data] [-h|--help] [-v|--version]"
    exit 1
+}
+
+
+# ###### Version ############################################################
+version () {
+   echo "HiPerConTracer-Node-Removal @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   exit 0
 }
 
 
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 1 ] ; then
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
+options="$(${GETOPT} -o rhv --long remove-data,help,version -a -- "$@")"
+# shellcheck disable=SC2181
+if [[ $? -ne 0 ]] ; then
+   usage 1
+fi
+
+REMOVE_DATA=0
+eval set -- "${options}"
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -r | --remove-data)
+         REMOVE_DATA=1
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      -v | --version)
+         version
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
+         ;;
+  esac
+  shift
+done
+if [ $# -ne 1 ] ; then
    usage
 fi
 
 NODE_ID="$1"
-shift
-
 if [[ ! "${NODE_ID}" =~ ^[0-9]+$ ]] ; then
    echo >&2 "ERROR: Invalid Node ID ${NODE_ID}!"
    exit 1
@@ -57,32 +102,6 @@ if [ "${NODE_ID}" -lt 1 ] || [ "${NODE_ID}" -gt 9999 ] ; then
    echo >&2 "ERROR: Invalid number for Node ID: ${NODE_ID}!"
    exit 1
 fi
-
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-options="$(${GETOPT} -o hr --long help,remove-data -a -- "$@")"
-# shellcheck disable=SC2181
-if [[ $? -ne 0 ]] ; then
-   usage
-fi
-
-REMOVE_DATA=0
-eval set -- "${options}"
-while [ $# -gt 0 ] ; do
-   case "$1" in
-      -h | --help)
-         usage
-         ;;
-      -r | --remove-data)
-         REMOVE_DATA=1
-         shift
-         ;;
-      --)
-         shift
-         break
-         ;;
-  esac
-done
-
 
 # ====== Remove user ========================================================
 user="node${NODE_ID}"
diff --git a/src/hpct-node-setup b/src/hpct-node-setup
--- a/src/hpct-node-setup
+++ b/src/hpct-node-setup
@@ -34,16 +34,67 @@ set -euo pipefail
 
 # ###### Usage ##############################################################
 usage () {
-   echo >&2 "Usage: $0 user@collector node_id [-h|--help] [--verbose|-v] [--quiet|-q]"
+   echo >&2 "Usage: $0 user@collector node_id [--quiet|-q] [--verbose|-w] [-h|--help] [-v|--version]"
    exit 1
 }
+
+
+# ###### Version ############################################################
+version () {
+   echo "HiPerConTracer-Node-Setup @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   exit 0
+}
+
 
 
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 2 ] ; then
-   usage
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
+options="$(${GETOPT} -o hv --long help,version -a -- "$@")"
+# shellcheck disable=SC2181
+if [[ $? -ne 0 ]]; then
+   usage 1
+fi
+eval set -- "${options}"
+
+VERBOSE=0
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -q | --quiet)
+         VERBOSE=0
+         ;;
+      -w | --verbose)
+         VERBOSE=1
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      -v | --version)
+         version
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
+         ;;
+  esac
+  shift
+done
+if [ $# -ne 2 ] ; then
+   usage 1
 fi
 
 COLLECTOR="$1"
@@ -77,35 +128,6 @@ if [ "${COLLECTOR}" == "" ] ; then
    exit 1
 fi
 
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-options="$(${GETOPT} -o hqvc --long help,quiet,verbose,copy-id -a -- "$@")"
-# shellcheck disable=SC2181
-if [[ $? -ne 0 ]] ; then
-   usage
-fi
-
-VERBOSE=0
-eval set -- "${options}"
-while [ $# -gt 0 ] ; do
-   case "$1" in
-      -h | --help)
-         usage
-         ;;
-      -v | --verbose)
-         VERBOSE=1
-         shift
-         ;;
-      -q | --quiet)
-         VERBOSE=0
-         shift
-         ;;
-      --)
-         shift
-         break
-         ;;
-  esac
-done
-
 
 # ====== Create server key ==================================================
 if [ ! -e "${SERVER_KEY}" ] ; then
@@ -113,8 +135,6 @@ if [ ! -e "${SERVER_KEY}" ] ; then
    exit 1
 fi
 
-# ====== Create key pair ====================================================
-# if [ "${VERBOSE}" -eq 1 ] ; then set -eux ; else set -eu ; fi
 echo -e "\x1b[34m$(date +"%Y-%m-%d %H:%M:%S") Checking local key pair ${PRIVATE_KEY} / ${PUBLIC_KEY} of Node ${NODE_ID} ...\x1b[0m"
 directory="$(dirname ${PRIVATE_KEY})"
 if sudo -u "${NODE_HIPERCONTRACER_USER}" test ! -d "${directory}" ; then
diff --git a/src/hpct-ssh b/src/hpct-ssh
--- a/src/hpct-ssh
+++ b/src/hpct-ssh
@@ -29,16 +29,69 @@ set -euo pipefail
 
 # ###### Usage ##############################################################
 usage () {
-   echo >&2 "Usage: $0 user@node_id [-h|--help] [--verbose|-v] [--quiet|-q] [--copy-id|-c] -- [ssh_arguments ...]"
+   echo >&2 "Usage: $0 user@node_id [--copy-id|-c] [--quiet|-q] [--verbose|-v] [-h|--help] [-v|--version] -- [ssh_arguments ...]"
    exit 1
 }
+
+
+# ###### Version ############################################################
+version () {
+   echo "HiPerConTracer-SSH @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   exit 0
+}
+
 
 
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 1 ] ; then
-   usage
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
+options="$(${GETOPT} -o cqwvh --long copy-id,quiet,verbose,copy-id -a -- "$@")"
+# shellcheck disable=SC2181
+if [[ $? -ne 0 ]] ; then
+   usage 1
+fi
+
+eval set -- "${options}"
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -c | --copy-id)
+         COPY_ID=1
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         ;;
+      -w | --verbose)
+         VERBOSE=1
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      -v | --version)
+         version
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
+         ;;
+  esac
+  shift
+done
+if [ $# -ne 1 ] ; then
+   usage 1
 fi
 
 # shellcheck disable=SC2001
@@ -61,38 +114,6 @@ if [ "${NODE_ID}" -lt 1 ] || [ "${NODE_ID}" -gt 9999 ] ; then
    echo >&2 "ERROR: Invalid number for Node ID: ${NODE_ID}!"
    exit 1
 fi
-
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-options="$(${GETOPT} -o hqvc --long help,quiet,verbose,copy-id -a -- "$@")"
-# shellcheck disable=SC2181
-if [[ $? -ne 0 ]] ; then
-   usage
-fi
-
-eval set -- "${options}"
-while [ $# -gt 0 ] ; do
-   case "$1" in
-      -c | --copy-id)
-         COPY_ID=1
-         shift 2
-         ;;
-      -h | --help)
-         usage
-         ;;
-      -v | --verbose)
-         VERBOSE=1
-         shift
-         ;;
-      -q | --quiet)
-         VERBOSE=0
-         shift
-         ;;
-      --)
-         shift
-         break
-         ;;
-  esac
-done
 
 
 # ====== SSH to node via Reverse Tunnel =====================================
diff --git a/src/hpct-sync b/src/hpct-sync
--- a/src/hpct-sync
+++ b/src/hpct-sync
@@ -34,19 +34,35 @@ set -euo pipefail
 
 # ###### Usage ##############################################################
 usage () {
-   echo >&2 "Usage: $0 [-h|--help] [--verbose|-v] [--quiet|-q] [--local|-L local_directory] [--remote|-R remote_location] [--collector|-C collector] [--key|-K ssh_private_key_file]"
+   echo >&2 "Usage: $0 [--verbose|-v] [--quiet|-q] [--local|-L local_directory] [--remote|-R remote_location] [--collector|-C collector] [--key|-K ssh_private_key_file] [-h|--help] [-v|--version]"
    exit 1
 }
+
+
+# ###### Version ############################################################
+version () {
+   echo "HiPerConTracer-Sync @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   exit 0
+}
+
 
 
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-options="$(${GETOPT} -o hN:L:R:C:K:H:vq --long help,nodeid:,local:,remote:,collector:,key:,known-hosts:,verbose,quiet -a -- "$@")"
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
+options="$(${GETOPT} -o hN:L:R:C:K:H:qwhv --long help,nodeid:,local:,remote:,collector:,key:,known-hosts:,quiet,verbose,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
-   usage
+   usage 1
 fi
 
 NODE_ID=
@@ -62,48 +78,55 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -N | --nodeid)
          NODE_ID="$2"
-         shift 2
+         shift
          ;;
       -L | --local)
          LOCAL="$2"
-         shift 2
+         shift
          ;;
       -R | --remote)
          REMOTE="$2"
-         shift 2
+         shift
          ;;
       -C | --collector)
          COLLECTOR="$2"
-         shift 2
+         shift
          ;;
       -K | --key)
          KEY="$2"
-         shift 2
+         shift
          ;;
       -H | --known-hosts)
          KNOWN_HOSTS="$2"
-         shift 2
-         ;;
-      -h | --help)
-         usage
-         ;;
-      -v | --verbose)
-         VERBOSE=1
          shift
+         ;;
+      -w | --verbose)
+         VERBOSE=1
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      -v | --version)
+         version
          ;;
       --)
          shift
          break
          ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
+         ;;
   esac
+  shift
 done
 
 if [ "${LOCAL}" == "" ] || [ "${REMOTE}" == "" ] || [ "${COLLECTOR}" == "" ] ; then
-   usage
+   usage 1
 fi
 if [ ! -d "${LOCAL}" ] ; then
    echo >&2 "ERROR: Local directory ${LOCAL} does not exist!"
diff --git a/src/make-dbeaver-configuration b/src/make-dbeaver-configuration
--- a/src/make-dbeaver-configuration
+++ b/src/make-dbeaver-configuration
@@ -32,42 +32,86 @@
 set -euo pipefail
 
 
+# ###### Usage ##############################################################
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 database_configuration_file ... [--join] [-h|--help] [-v|--version]"
+   exit "${exitCode}"
+}
+
+
+# ###### Version ############################################################
+version () {
+   echo "Make-DBeaver-Configuration @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
+   exit 0
+}
+
+
+
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 1 ] ; then
-   echo >&2 "Usage: $0 database_configuration_file ... [--join]"
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
+   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} installed!"
    exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
+options="$(${GETOPT} -o jhv --long join,help,version -a -- "$@")"
+# shellcheck disable=SC2181
+if [[ $? -ne 0 ]]; then
+   usage 1
+fi
+
+JOIN=0
+eval set -- "${options}"
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -j | --join)
+         JOIN=1
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      -v | --version)
+         version
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
+         ;;
+  esac
+done
+if [ $# -lt 1 ] ; then
+   usage 1
 fi
 DIRNAME="$(dirname "$0")"
 
 
-# ====== Generate DBeaver configuration files ===============================
+# ====== Process configuration files ========================================
 echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Generating DBeaver configuration ...\x1b[0m"
 tempDirectory="$(mktemp -d -t "make-dbeaver-configuration-XXXXXX")"
 trap 'rm -rf "${tempDirectory}"' EXIT
 
-join=0
 dbeaverConfig=""
 dbeaverCredentials=""
 while [ $# -gt 0 ] ; do
-   if [[ "$1" =~ ^-- ]] ; then
-      if [ "$1" == "--join"  ] ; then
-         join=1
-      else
-         echo >&2 "ERROR: Invalid option $1!"
-         exit 1
-      fi
-   else
-      echo -e "\x1b[37mProcessing $(basename "$1") ...\x1b[0m"
-      "$(dirname "$0")"/dbshell "$1" --dry-run -q -B "${tempDirectory}/$(basename "${1//.conf/}")"
-   fi
+   echo -e "\x1b[37mProcessing $(basename "$1") ...\x1b[0m"
+   "${DIRNAME}/dbshell" "$1" --dry-run --quiet --write-dbeaver-config "${tempDirectory}/$(basename "${1//.conf/}")"
    shift
 done
 
 
 # ====== Read existing configuration ========================================
-if [ ${join} -eq 1 ] ; then
+if [ ${JOIN} -eq 1 ] ; then
    echo -e "\x1b[37mLooking for existing DBeaver configuration ...\x1b[0m"
    for dbeaverDirectory in \
       "${HOME}/snap/dbeaver-ce/current/.local/share/DBeaverData/workspace6/General/.dbeaver" \
@@ -80,7 +124,7 @@ if [ ${join} -eq 1 ] ; then
          if [ -e "${dbeaverDirectory}/credentials-config.json" ] ; then
             dbeaverCredentials="${tempDirectory}/credentials-config.json"
             echo -e "\x1b[37mJoining credentials in ${dbeaverDirectory}/credentials-config.json\x1b[0m"
-            "${DIRNAME}"/decrypt-dbeaver-configuration \
+            "${DIRNAME}/decrypt-dbeaver-configuration" \
                "${dbeaverDirectory}/credentials-config.json" \
                "${dbeaverCredentials}"
          fi
@@ -102,13 +146,13 @@ jq --sort-keys --slurp 'reduce .[] as $item ({}; . * $item)' ${dbeaverConfig}   
 jq --sort-keys --slurp 'reduce .[] as $item ({}; . * $item)' ${dbeaverCredentials} "${tempDirectory}"/*-credentials-config.json >"${tempDirectory}/credentials-config.json.plaintext"
 
 # Encrypt the new credentials files:
-"${DIRNAME}"/encrypt-dbeaver-configuration \
+"${DIRNAME}/encrypt-dbeaver-configuration" \
    "${tempDirectory}/credentials-config.json.plaintext" \
    "${tempDirectory}/credentials-config.json"
 
 
 # ====== Join with existing configuration ===================================
-if [ ${join} -eq 1 ] ; then
+if [ ${JOIN} -eq 1 ] ; then
    if [ "${dbeaverConfig}" != "" ] ; then
       if ! diff "${tempDirectory}/data-sources.json" "${dbeaverDirectory}/data-sources.json" >/dev/null ; then
          dbeaverConfigBackup="${dbeaverConfig}.backup-$(date +"%F-%H:%M:%S")"
