Bugfix: DBShell needs to check whether client is available. To prevent installing unnecessary DB packages, the clients are not strict dependencies.

diff --git a/src/dbshell b/src/dbshell
--- a/src/dbshell
+++ b/src/dbshell
@@ -124,12 +124,14 @@ if [ "${dbbackend}" == "MariaDB" ] || [ "${dbbackend}" == "MySQL" ] ; then
    if [ "${dbbackend}" == "MariaDB" ] ; then
       command="$(which mariadb || true)"
       if [ "${command}" == "" ] ; then
-         command="mariadb"
+         echo >&2 "ERROR: MariaDB client (mariadb) not found. Is it installed?"
+         exit 1
       fi
    else
       command="$(which mysql || true)"
       if [ "${command}" == "" ] ; then
-         command="mysql"
+         echo >&2 "ERROR: MySQL client (mysql) not found. Is it installed?"
+         exit 1
       fi
    fi
    if [ "${dbport}" == "0" ] ; then
@@ -150,7 +152,8 @@ elif [ "${dbbackend}" == "PostgreSQL" ] ; then
 
    command="$(which psql || true)"
    if [ "${command}" == "" ] ; then
-      command="psql"
+      echo >&2 "ERROR: PostgreSQL client (psql) not found. Is it installed?"
+      exit 1
    fi
    if [ "${dbport}" == "0" ] ; then
       dbport="5432"
@@ -181,7 +184,8 @@ elif [ "${dbbackend}" == "MongoDB" ] ; then
    if [ "${command}" == "" ] ; then
       command="$(which mongo || true)"
       if [ "${command}" == "" ] ; then
-         command="mongosh"
+         echo >&2 "ERROR: MongoDB client (mongosh or mongo) not found. Is it installed?"
+         exit 1
       else
          oldCommand=1
       fi
