Further configuration improvements.

diff --git a/src/dbshell b/src/dbshell
--- a/src/dbshell
+++ b/src/dbshell
@@ -32,15 +32,25 @@
 set -euo pipefail
 
 
-# ###### Get absolute path name of file relative to directory ###############
-make-abspath () {
+# ###### Make absolute path name of file, and check its existence ###########
+check-file () {
    local file="$1"
    local directory="$2"
-   if [[ "${file}" =~ ^(/) ]] ; then
-      echo "${file}"
+   local label="$3"
+
+   if [[ "${file^^}" =~ ^(NONE|IGNORE|)$ ]] ; then
+      file=""
    else
-      echo "${directory}/${file}"
+      if [[ ! "${file}" =~ ^(/) ]] ; then
+         file="${directory}/${file}"
+      fi
+      if [ ! -f "${file}" ] ; then
+         echo >&2 "ERROR: Unable to find ${label} ${file}!"
+         exit 1
+      fi
    fi
+
+   echo "${file}"
 }
 
 
@@ -158,31 +168,13 @@ dbpassword=""
 database=""
 configContent=$(sed -r '/[^=#]+=[^=]+/!d' <"${CONFIGURATION_FILE}" | sed -r "s/[[:space:]]*=[[:space:]]*(.*)[[:space:]]*/='\1'/g")
 eval "${configContent}"
-if [ "${dbcafile}" == "NONE" ] ; then
-   dbcafile=""
-else
-   dbcafile="$(make-abspath "${dbcafile}" "${CONFIGURATION_DIRECTORY}")"
-fi
-if [ "${dbcrlfile}" == "NONE" ] ; then
-   dbcrlfile=""
-else
-   dbcrlfile="$(make-abspath "${dbcrlfile}" "${CONFIGURATION_DIRECTORY}")"
-fi
-if [ "${dbkeyfile}" == "NONE" ] ; then
-   dbkeyfile=""
-else
-   dbkeyfile="$(make-abspath "${dbkeyfile}" "${CONFIGURATION_DIRECTORY}")"
-fi
-if [ "${dbcertfile}" == "NONE" ] ; then
-   dbcertfile=""
-else
-   dbcertfile="$(make-abspath "${dbcertfile}" "${CONFIGURATION_DIRECTORY}")"
-fi
-if [ "${dbcertkeyfile}" == "NONE" ] ; then
-   dbcertkeyfile=""
-else
-   dbcertkeyfile="$(make-abspath "${dbcertkeyfile}" "${CONFIGURATION_DIRECTORY}")"
-fi
+
+dbcafile="$(check-file "${dbcafile}" "${CONFIGURATION_DIRECTORY}" "CA certificate file (dbcafile setting)")"
+dbcrlfile="$(check-file "${dbcrlfile}" "${CONFIGURATION_DIRECTORY}" "CRL file (dbcrlfile setting)")"
+dbkeyfile="$(check-file "${dbkeyfile}" "${CONFIGURATION_DIRECTORY}" "key file (dbkeyfile setting)")"
+dbcertfile="$(check-file "${dbcertfile}" "${CONFIGURATION_DIRECTORY}" "certificertte file (dbcertfile setting)")"
+dbcertkeyfile="$(check-file "${dbcertkeyfile}" "${CONFIGURATION_DIRECTORY}" "certificertkeyte+key file (dbcertkeyfile setting)")"
+
 tls_enabled=1
 tls_check_certificate=1
 tls_check_hostname=1
