Improved scripts.

diff --git a/src/make-dbeaver-configuration b/src/make-dbeaver-configuration
--- a/src/make-dbeaver-configuration
+++ b/src/make-dbeaver-configuration
@@ -31,7 +31,7 @@
 #  Contact: dreibh@simula.no
 
 # Bash options:
-set -e
+set -eu
 
 
 # ====== Handle arguments ===================================================
@@ -44,26 +44,33 @@ fi
 # ====== Generate DBeaver configuration files ===============================
 echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Generating DBeaver configuration ...\x1b[0m"
 tempDirectory="$(mktemp -d -t "make-dbeaver-configuration-XXXXXX")"
+
 dbeaverConfig=""
 dbeaverCredentials=""
+for dbeaverDirectory in "${HOME}/snap/dbeaver-ce/current/.local/share/DBeaverData/workspace6/General/.dbeaver" "${HOME}/.local/share/DBeaverData/workspace6/General/.dbeaver" ; do
+   if [ -e "${dbeaverDirectory}" ] ; then
+      if [ -e "${dbeaverDirectory}/data-sources.json" ] ; then
+         dbeaverConfig="${dbeaverDirectory}/data-sources.json"
+         echo -e "\x1b[37mJoining data sources in ${dbeaverConfig}\x1b[0m"
+      fi
+      if [ -e "${dbeaverDirectory}/credentials-config.json" ] ; then
+         dbeaverCredentials="${tempDirectory}/credentials-config.json"
+         echo -e "\x1b[37mJoining credentials in ${dbeaverDirectory}/credentials-config.json\x1b[0m"
+         openssl aes-128-cbc -d \
+            -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 \
+            -in "${dbeaverDirectory}/credentials-config.json" | dd bs=1 skip=16 2>/dev/null | jq . >"${dbeaverCredentials}"
+      fi
+      break
+   fi
+done
+if [ ! -e "${dbeaverDirectory}" ] ; then
+   echo >&2 "ERROR: Unable to find DBeaver configuration directory!"
+   exit 1
+fi
+
 while [ $# -gt 0 ] ; do
-   if [ "$1" == "--join" ] ; then
-      for dbeaverDirectory in "${HOME}/snap/dbeaver-ce/current/.local/share/DBeaverData/workspace6/General/.dbeaver/" "${HOME}/.local/share/DBeaverData/workspace6/General/.dbeaver/" ; do
-         if [ -e "${dbeaverDirectory}" ] ; then
-            if [ -e "${dbeaverDirectory}/data-sources.json" ] ; then
-               dbeaverConfig="${dbeaverDirectory}/data-sources.json"
-               echo -e "\x1b[37mJoining data sources in ${dbeaverConfig}\x1b[0m"
-            fi
-            if [ -e "${dbeaverDirectory}/credentials-config.json" ] ; then
-               dbeaverCredentials="${tempDirectory}/credentials-config.json"
-               echo -e "\x1b[37mJoining credentials in ${dbeaverDirectory}/credentials-config.json\x1b[0m"
-               openssl aes-128-cbc -d \
-                  -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 \
-                  -in "${dbeaverDirectory}/credentials-config.json" | dd bs=1 skip=16 2>/dev/null | jq . >"${dbeaverCredentials}"
-            fi
-            break
-         fi
-      done
+   if [[ "$1" =~ "^--" ]] ; then
+      true
    else
       echo -e "\x1b[37mProcessing $(basename "$1") ...\x1b[0m"
       "$(dirname "$0")"/dbshell "$1" --dry-run -q -B "${tempDirectory}/$(basename "${1//.conf/}")"
@@ -82,7 +89,6 @@ jq --sort-keys --slurp 'reduce .[] as $item ({}; . * $item)' ${dbeaverCredential
 # credentials-config.json.in is in plain text.
 # DBeaver expects a simple encrypted file:
 dd if=/dev/urandom of="${tempDirectory}/credentials-config.json.in" bs=16 count=1 2>/dev/null   # 16 bytes random number
-# dd if="${tempDirectory}/credentials-config.json.orig" of="${tempDirectory}/credentials-config.json.in" oflag=append conv=notrunc 2>/dev/null
 cat "${tempDirectory}/credentials-config.json.orig" >>"${tempDirectory}/credentials-config.json.in"
 openssl aes-128-cbc \
    -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 \
@@ -96,27 +102,25 @@ openssl aes-128-cbc \
 
 
 # ====== Replace configurations =============================================
-if [ -e "${dbeaverDirectory}" ] ; then
-   if [ "${dbeaverConfig}" != "" ] ; then
-      if ! diff data-sources.json "${dbeaverDirectory}/data-sources.json" >/dev/null ; then
-         dbeaverConfigBackup="${dbeaverConfig}.backup-$(date +"%F-%H:%M:%S")"
-         echo -e "\x1b[37mMaking data sources backup in ${dbeaverConfigBackup} ...\x1b[0m"
-         cp "${dbeaverConfig}" "${dbeaverConfigBackup}"
-      fi
+if [ "${dbeaverConfig}" != "" ] ; then
+   if ! diff data-sources.json "${dbeaverDirectory}/data-sources.json" >/dev/null ; then
+      dbeaverConfigBackup="${dbeaverConfig}.backup-$(date +"%F-%H:%M:%S")"
+      echo -e "\x1b[37mMaking data sources backup in ${dbeaverConfigBackup} ...\x1b[0m"
+      cp "${dbeaverConfig}" "${dbeaverConfigBackup}"
    fi
-   echo -e "\x1b[37mUpdating data sources ${dbeaverDirectory}/data-sources.json ...\x1b[0m"
-   cp data-sources.json "${dbeaverDirectory}/data-sources.json"
-
-   if [ "${dbeaverCredentials}" != "" ] ; then
-      if ! diff "${dbeaverCredentials}" "${tempDirectory}/credentials-config.json.orig" >/dev/null ; then
-         dbeaverCredentialsBackup="${dbeaverDirectory}/credentials-config.json-$(date +"%F-%H:%M:%S")"
-         echo -e "\x1b[37mKeeping backup in ${dbeaverCredentialsBackup} ...\x1b[0m"
-         cp "${dbeaverCredentials}" "${dbeaverCredentialsBackup}"
-      fi
-   fi
-   echo -e "\x1b[37mUpdating credentials ${dbeaverDirectory}/credentials-config.json ...\x1b[0m"
-   cp credentials-config.json "${dbeaverDirectory}/credentials-config.json"
 fi
+echo -e "\x1b[37mUpdating data sources ${dbeaverDirectory}/data-sources.json ...\x1b[0m"
+cp data-sources.json "${dbeaverDirectory}/data-sources.json"
+
+if [ "${dbeaverCredentials}" != "" ] ; then
+   if ! diff "${dbeaverCredentials}" "${tempDirectory}/credentials-config.json.orig" >/dev/null ; then
+      dbeaverCredentialsBackup="${dbeaverDirectory}/credentials-config.json-$(date +"%F-%H:%M:%S")"
+      echo -e "\x1b[37mKeeping backup in ${dbeaverCredentialsBackup} ...\x1b[0m"
+      cp "${dbeaverCredentials}" "${dbeaverCredentialsBackup}"
+   fi
+fi
+echo -e "\x1b[37mUpdating credentials ${dbeaverDirectory}/credentials-config.json ...\x1b[0m"
+cp credentials-config.json "${dbeaverDirectory}/credentials-config.json"
 
 
 # ====== Clean up ===========================================================
