Improved script.

diff --git a/src/make-dbeaver-configuration b/src/make-dbeaver-configuration
--- a/src/make-dbeaver-configuration
+++ b/src/make-dbeaver-configuration
@@ -35,42 +35,29 @@ set -eu
 
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 2 ] ; then
+if [ $# -lt 1 ] ; then
    echo >&2 "Usage: $0 database_configuration_file ..."
    exit 1
 fi
+DIRNAME="$(dirname "$0")"
 
 
 # ====== Generate DBeaver configuration files ===============================
 echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Generating DBeaver configuration ...\x1b[0m"
 tempDirectory="$(mktemp -d -t "make-dbeaver-configuration-XXXXXX")"
+trap 'rm -rf "${tempDirectory}"' EXIT
 
+join=0
 dbeaverConfig=""
 dbeaverCredentials=""
-for dbeaverDirectory in "${HOME}/snap/dbeaver-ce/current/.local/share/DBeaverData/workspace6/General/.dbeaver" "${HOME}/.local/share/DBeaverData/workspace6/General/.dbeaver" ; do
-   if [ -e "${dbeaverDirectory}" ] ; then
-      if [ -e "${dbeaverDirectory}/data-sources.json" ] ; then
-         dbeaverConfig="${dbeaverDirectory}/data-sources.json"
-         echo -e "\x1b[37mJoining data sources in ${dbeaverConfig}\x1b[0m"
-      fi
-      if [ -e "${dbeaverDirectory}/credentials-config.json" ] ; then
-         dbeaverCredentials="${tempDirectory}/credentials-config.json"
-         echo -e "\x1b[37mJoining credentials in ${dbeaverDirectory}/credentials-config.json\x1b[0m"
-         openssl aes-128-cbc -d \
-            -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 \
-            -in "${dbeaverDirectory}/credentials-config.json" | dd bs=1 skip=16 2>/dev/null | jq . >"${dbeaverCredentials}"
-      fi
-      break
-   fi
-done
-if [ ! -e "${dbeaverDirectory}" ] ; then
-   echo >&2 "ERROR: Unable to find DBeaver configuration directory!"
-   exit 1
-fi
-
 while [ $# -gt 0 ] ; do
-   if [[ "$1" =~ "^--" ]] ; then
-      true
+   if [[ "$1" =~ ^-- ]] ; then
+      if [ "$1" == "--join"  ] ; then
+         join=1
+      else
+         echo >&2 "ERROR: Invalid option $1!"
+         exit 1
+      fi
    else
       echo -e "\x1b[37mProcessing $(basename "$1") ...\x1b[0m"
       "$(dirname "$0")"/dbshell "$1" --dry-run -q -B "${tempDirectory}/$(basename "${1//.conf/}")"
@@ -79,48 +66,77 @@ while [ $# -gt 0 ] ; do
 done
 
 
-# ====== Join DBeaver configuration files ===================================
+# ====== Read existing configuration ========================================
+if [ ${join} -eq 1 ] ; then
+   echo -e "\x1b[37mLooking for existing DBeaver configuration ...\x1b[0m"
+   for dbeaverDirectory in \
+      "${HOME}/snap/dbeaver-ce/current/.local/share/DBeaverData/workspace6/General/.dbeaver" \
+      "${HOME}/.local/share/DBeaverData/workspace6/General/.dbeaver" ; do
+      if [ -e "${dbeaverDirectory}" ] ; then
+         if [ -e "${dbeaverDirectory}/data-sources.json" ] ; then
+            dbeaverConfig="${dbeaverDirectory}/data-sources.json"
+            echo -e "\x1b[37mJoining data sources in ${dbeaverConfig}\x1b[0m"
+         fi
+         if [ -e "${dbeaverDirectory}/credentials-config.json" ] ; then
+            dbeaverCredentials="${tempDirectory}/credentials-config.json"
+            echo -e "\x1b[37mJoining credentials in ${dbeaverDirectory}/credentials-config.json\x1b[0m"
+            "${DIRNAME}"/decrypt-dbeaver-configuration \
+               "${dbeaverDirectory}/credentials-config.json" \
+               "${dbeaverCredentials}"
+         fi
+         break
+      fi
+   done
+   if [ ! -e "${dbeaverDirectory}" ] ; then
+      echo >&2 "ERROR: Unable to find DBeaver configuration directory!"
+      exit 1
+   fi
+fi
+
+
+# ====== Join new DBeaver configuration files ===============================
 echo -e "\x1b[37mJoining configurations ...\x1b[0m"
 # shellcheck disable=SC2086
-jq --sort-keys --slurp 'reduce .[] as $item ({}; . * $item)' ${dbeaverConfig}      "${tempDirectory}"/*-data-source.json >data-sources.json
+jq --sort-keys --slurp 'reduce .[] as $item ({}; . * $item)' ${dbeaverConfig}      "${tempDirectory}"/*-data-source.json >"${tempDirectory}/data-sources.json"
 # shellcheck disable=SC2086
-jq --sort-keys --slurp 'reduce .[] as $item ({}; . * $item)' ${dbeaverCredentials} "${tempDirectory}"/*-credentials-config.json >"${tempDirectory}/credentials-config.json.orig"
+jq --sort-keys --slurp 'reduce .[] as $item ({}; . * $item)' ${dbeaverCredentials} "${tempDirectory}"/*-credentials-config.json >"${tempDirectory}/credentials-config.json.plaintext"
 
-# credentials-config.json.in is in plain text.
-# DBeaver expects a simple encrypted file:
-dd if=/dev/urandom of="${tempDirectory}/credentials-config.json.in" bs=16 count=1 2>/dev/null   # 16 bytes random number
-cat "${tempDirectory}/credentials-config.json.orig" >>"${tempDirectory}/credentials-config.json.in"
-openssl aes-128-cbc \
-   -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 \
-   -in "${tempDirectory}/credentials-config.json.in" >credentials-config.json
-
-# To decrypt:
-# (See also: https://stackoverflow.com/questions/39928401/recover-db-password-stored-in-my-dbeaver-connection)
-# openssl aes-128-cbc -d \
-#    -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 \
-#    -in credentials-config.json | dd bs=1 skip=16 | jq .
+# Encrypt the new credentials files:
+"${DIRNAME}"/encrypt-dbeaver-configuration \
+   "${tempDirectory}/credentials-config.json.plaintext" \
+   "${tempDirectory}/credentials-config.json"
 
 
-# ====== Replace configurations =============================================
-if [ "${dbeaverConfig}" != "" ] ; then
-   if ! diff data-sources.json "${dbeaverDirectory}/data-sources.json" >/dev/null ; then
-      dbeaverConfigBackup="${dbeaverConfig}.backup-$(date +"%F-%H:%M:%S")"
-      echo -e "\x1b[37mMaking data sources backup in ${dbeaverConfigBackup} ...\x1b[0m"
-      cp "${dbeaverConfig}" "${dbeaverConfigBackup}"
+# ====== Join with existing configuration ===================================
+if [ ${join} -eq 1 ] ; then
+   if [ "${dbeaverConfig}" != "" ] ; then
+      if ! diff "${tempDirectory}/data-sources.json" "${dbeaverDirectory}/data-sources.json" >/dev/null ; then
+         dbeaverConfigBackup="${dbeaverConfig}.backup-$(date +"%F-%H:%M:%S")"
+         echo -e "\x1b[37mMaking data sources backup in ${dbeaverConfigBackup} ...\x1b[0m"
+         cp "${dbeaverConfig}" "${dbeaverConfigBackup}"
+      fi
    fi
-fi
-echo -e "\x1b[37mUpdating data sources ${dbeaverDirectory}/data-sources.json ...\x1b[0m"
-cp data-sources.json "${dbeaverDirectory}/data-sources.json"
+   echo -e "\x1b[37mUpdating data sources ${dbeaverDirectory}/data-sources.json ...\x1b[0m"
+   mv "${tempDirectory}/data-sources.json" "${dbeaverDirectory}/data-sources.json"
 
-if [ "${dbeaverCredentials}" != "" ] ; then
-   if ! diff "${dbeaverCredentials}" "${tempDirectory}/credentials-config.json.orig" >/dev/null ; then
-      dbeaverCredentialsBackup="${dbeaverDirectory}/credentials-config.json-$(date +"%F-%H:%M:%S")"
-      echo -e "\x1b[37mKeeping backup in ${dbeaverCredentialsBackup} ...\x1b[0m"
-      cp "${dbeaverCredentials}" "${dbeaverCredentialsBackup}"
+   if [ "${dbeaverCredentials}" != "" ] ; then
+      if ! diff "${dbeaverCredentials}" "${tempDirectory}/credentials-config.json.plaintext" >/dev/null ; then
+         dbeaverCredentialsBackup="${dbeaverDirectory}/credentials-config.json-$(date +"%F-%H:%M:%S")"
+         echo -e "\x1b[37mKeeping backup in ${dbeaverCredentialsBackup} ...\x1b[0m"
+         cp "${dbeaverCredentials}" "${dbeaverCredentialsBackup}"
+      fi
    fi
+   echo -e "\x1b[37mUpdating credentials ${dbeaverDirectory}/credentials-config.json ...\x1b[0m"
+   mv "${tempDirectory}/credentials-config.json" "${dbeaverDirectory}/credentials-config.json"
+
+else
+
+   # Just generated the configuration files -> no joining was performed!
+   mv "${tempDirectory}/data-sources.json" "${tempDirectory}/credentials-config.json" .
+   echo "Generated configuration files:"
+   ls -l credentials-config.json data-sources.json
+
 fi
-echo -e "\x1b[37mUpdating credentials ${dbeaverDirectory}/credentials-config.json ...\x1b[0m"
-cp credentials-config.json "${dbeaverDirectory}/credentials-config.json"
 
 
 # ====== Clean up ===========================================================
