Improved dependency installation hints.

diff --git a/src/run-shellcheck b/src/run-shellcheck
--- a/src/run-shellcheck
+++ b/src/run-shellcheck
@@ -34,8 +34,11 @@ set -euo pipefail
 # Automatically find all shell scripts in subdirectories:
 SCRIPTS="$(
 (
-   find . -type f -executable -and -not -name "*~"
-   find . -name "*.bash-completion" -and -not -name "*~"
+   find . -path '*/.*' -type d -prune \
+      -o \( \
+            \( -type f -perm -100 ! -name "*~" \) \
+            -o -name "*.bash-completion" \
+         \) -print
 ) | while read -r name ; do
    if [[ "$(head -n1 "${name}" | strings)" =~ (bash|/bin/sh) ]] ; then
       echo "${name}"
@@ -95,29 +98,40 @@ show-script ()
 # ###### Main program #######################################################
 
 # ====== Find locations of Python interpreter, MyPy, and tools ==============
-if ! command -v shellcheck 2>/dev/null ; then
-   echo >&2 "ERROR: ShellCheck is not installed!"
-   echo >&2 "Try this:"
-   echo >&2 "* Ubuntu:  sudo apt install -y shellcheck"
-   echo >&2 "* Fedora:  sudo dnf install -y ShellCheck"
-   echo >&2 "* FreeBSD: sudo pkg install -y hs-ShellCheck"
-   exit 1
-fi
 if ! command -v print-utf8 2>/dev/null ; then
-   echo >&2 "ERROR: Print-UTF8 (from System-Tools) is not installed!"
-   echo >&2 "Try this:"
-   echo >&2 "* Ubuntu:  sudo apt-add-repository -sy ppa:dreibh/ppa"
+   echo >&2 "ERROR: Print-UTF8 (from System-Tools) is not installed! Try:"
+   echo >&2 " * Ubuntu:  sudo apt-add-repository -sy ppa:dreibh/ppa"
    echo >&2 "           sudo apt install -y td-system-tools"
-   echo >&2 "* Fedora:  sudo dnf copr enable -y dreibh/ppa"
+   echo >&2 " * Fedora:  sudo dnf copr enable -y dreibh/ppa"
    echo >&2 "           sudo dnf install -y td-system-tools"
-   echo >&2 "* FreeBSD: sudo pkg install -y td-system-tools"
+   echo >&2 " * FreeBSD: sudo pkg install -y td-system-tools"
+   echo >&2 " * See https://www.nntb.no/~dreibh/system-tools/#binary-package-installation for other systems!"
    exit 1
 fi
-if ! command -v figlet 2>/dev/null ; then
-   echo >&2 "ERROR: Figlet is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y figlet"
-   echo >&2 "* Fedora:  sudo dnf install -y figlet"
-   echo >&2 "* FreeBSD: sudo pkg install -y figlet"
+if ! command -v figlet >/dev/null ; then
+   echo >&2 "ERROR: Figlet is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y figlet"
+   echo >&2 " * Fedora:        sudo dnf install -y figlet"
+   echo >&2 " * OpenSUSE:      sudo zypper install -y figlet"
+   echo >&2 " * Alpine:        sudo apk add figlet"
+   echo >&2 " * FreeBSD:       sudo pkg install -y figlet"
+   echo >&2 " * NetBSD:        sudo pkgin -y install figlet"
+   echo >&2 " * OpenBSD:       sudo pkg_add figlet"
+   echo >&2 " * Solaris:       (install from sources)"
+   echo >&2 " * Apple:         brew install figlet"
+   exit 1
+fi
+if ! command -v shellcheck 2>/dev/null ; then
+   echo >&2 "ERROR: ShellCheck is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y shellcheck"
+   echo >&2 " * Fedora:        sudo dnf install -y ShellCheck"
+   echo >&2 " * OpenSUSE:      sudo zypper install -y ShellCheck"
+   echo >&2 " * Alpine:        sudo apk add shellcheck"
+   echo >&2 " * FreeBSD:       sudo pkg install -y hs-ShellCheck"
+   echo >&2 " * NetBSD:        sudo pkgin -y install shellcheck"
+   echo >&2 " * OpenBSD:       sudo pkg_add shellcheck"
+   echo >&2 " * Solaris:       (install from sources)"
+   echo >&2 " * Apple:         brew install shellcheck"
    exit 1
 fi
 
