Updated test scripts.

diff --git a/src/run-importer-test b/src/run-importer-test
--- a/src/run-importer-test
+++ b/src/run-importer-test
@@ -7,24 +7,29 @@ set -euo pipefail
 # under examples/. The result can be checked by run-query-test, which generates
 # HiPerConTracer data statements as in the input files.
 
-if [ $# -ne 1 ] ; then
-   echo >&2 "Usage: $0 configuration_file"
+if [ $# -ne 2 ] ; then
+   echo >&2 "Usage: $0 database_configuration_file importer_configuration_file"
    exit 1
 fi
-CONFIGURATION_FILE="$1"
-if [ ! -e "${CONFIGURATION_FILE}" ] ; then
-   echo >&2 "ERROR: Use configuration $1 does not exist!"
+DATABASE_CONFIGURATION_FILE="$1"
+if [ ! -e "${DATABASE_CONFIGURATION_FILE}" ] ; then
+   echo >&2 "ERROR: Use database configuration ${DATABASE_CONFIGURATION_FILE} does not exist!"
+fi
+IMPORTER_CONFIGURATION_FILE="$2"
+if [ ! -e "${IMPORTER_CONFIGURATION_FILE}" ] ; then
+   echo >&2 "ERROR: Use importer configuration ${IMPORTER_CONFIGURATION_FILE} does not exist!"
 fi
 
 mkdir -p data/ good/ bad/
 rm -rf good/*
 rm -rf bad/*
-cp examples/*.bz2 data/
+cp results-examples/*.hpct* data/
 
 make hpct-importer && \
 rm -f core &&  \
 ./hpct-importer \
-   -c "${CONFIGURATION_FILE}" \
+   -C "${IMPORTER_CONFIGURATION_FILE}" \
+   -D "${DATABASE_CONFIGURATION_FILE}" \
    --traceroute-workers 1 \
    --ping-workers 1 \
    --loglevel 0 \
diff --git a/src/run-query-test b/src/run-query-test
--- a/src/run-query-test
+++ b/src/run-query-test
@@ -8,24 +8,24 @@ set -euo pipefail
 # Limitation: only the headers #T, #P are compared, not the Traceroute hops!!
 
 if [ $# -ne 1 ] ; then
-   echo >&2 "Usage: $0 configuration_file"
+   echo >&2 "Usage: $0 database_configuration_file"
    exit 1
 fi
-CONFIGURATION_FILE="$1"
-if [ ! -e "${CONFIGURATION_FILE}" ] ; then
-   echo >&2 "ERROR: Use configuration $1 does not exist!"
+DATABASE_CONFIGURATION_FILE="$1"
+if [ ! -e "${DATABASE_CONFIGURATION_FILE}" ] ; then
+   echo >&2 "ERROR: Use database configuration ${DATABASE_CONFIGURATION_FILE} does not exist!"
 fi
 
 
 for type in Ping Traceroute ; do
 
    echo "Obtaining ${type} data from good/ directory ..."
-   find good/ -name "${type}-*.bz2" | sort | xargs -r bzcat | tee imported-raw-${type,,}.txt | grep "^#" | sort -k4 >imported-${type,,}.txt
+   find good/ -name "${type}-*.hpct*" | sort | xargs -r less | tee imported-raw-${type,,}.txt | grep "^#" | sort -k4 >imported-${type,,}.txt
    # ls -l imported-raw-${type,,}.txt imported-${type,,}.txt
 
 
    echo "Querying ${type} data from database ..."
-   ./hpct-query "${CONFIGURATION_FILE}" ${type,,} | tee queried-raw-${type,,}.txt | grep "^#" | sort -k4 >queried-${type,,}.txt
+   ./hpct-query "${DATABASE_CONFIGURATION_FILE}" ${type,,} | tee queried-raw-${type,,}.txt | grep "^#" | sort -k4 >queried-${type,,}.txt
    # ls -l queried-raw-${type,,}.txt queried-${type,,}.txt
 
    echo "Differences for ${type}:"
@@ -33,6 +33,6 @@ for type in Ping Traceroute ; do
       ls -l imported-raw-${type,,}.txt
       ls -l queried-raw-${type,,}.txt
    fi
-   colordiff imported-${type,,}.txt queried-${type,,}.txt
+   diff --color imported-${type,,}.txt queried-${type,,}.txt
 
 done
